version: '3.8'
services:
    test-mysql:
        image: 'mysql:5.7'
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 654654
            MYSQL_DATABASE: testDB
            MYSQL_USER: shin
            MYSQL_PASSWORD: 654654
            TZ: Asia/Seoul
        ports:
            - "3308:3306"
        container_name: test-mysql
        command:
            - --character-set-server=utf8
            - --collation-server=utf8_general_ci        